feature-flags:
  enabled: true
  api:
    expose:
      enabled: true
      endpoint: /feature-flags
    manage:
      enabled: true
      endpoint: /admin/feature-flags
  definitions:
    - name: DUPA
      enabled: ON
